server {
    listen 80 default_server;
    server_name _;
    include /etc/nginx/conf.d/nginx-site-routes.inc;
}

server {
    listen 80;
    server_name avatar-tech.com www.avatar-tech.com;
    return 301 https://www.avatar-tech.com$request_uri;
}

server {
    listen 443 ssl;
    server_name avatar-tech.com www.avatar-tech.com;

    ssl_certificate /etc/nginx/tls/avatar-tech.com.pem;
    ssl_certificate_key /etc/nginx/tls/avatar-tech.com.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    add_header Strict-Transport-Security "max-age=31536000" always;
    include /etc/nginx/conf.d/nginx-site-routes.inc;
}
