<template>
  <div class="app-container">
    <section class="credential-banner"><div><p>OFFICIAL SITE OPERATIONS</p><h2>资质证书与发布</h2><span>证书文件仅在被当前已发布版本引用时才能被官网访问。</span></div><el-button type="primary" icon="Plus" @click="handleAdd" v-hasPermi="['site:credential:add']">新增证书</el-button></section>
    <el-form ref="queryRef" :model="queryParams" :inline="true"><el-form-item label="证书编码"><el-input v-model="queryParams.credentialCode" clearable @keyup.enter="handleQuery" /></el-form-item><el-form-item label="类型"><el-select v-model="queryParams.credentialType" clearable><el-option v-for="item in types" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button><el-button icon="Refresh" @click="resetQuery">重置</el-button></el-form-item></el-form>
    <el-table v-loading="loading" :data="credentialList"><el-table-column label="证书编码" prop="credentialCode" min-width="270"/><el-table-column label="类型" min-width="150"><template #default="scope"><el-tag effect="plain">{{ labelFor(scope.row.credentialType) }}</el-tag></template></el-table-column><el-table-column label="草稿" width="105"><template #default="scope"><el-tag :type="scope.row.draftRevisionId ? 'warning' : 'info'" effect="plain">{{ scope.row.draftRevisionId ? '待发布' : '无草稿' }}</el-tag></template></el-table-column><el-table-column label="前台版本" width="110"><template #default="scope"><el-tag :type="scope.row.publishedRevisionId ? 'success' : 'info'" effect="plain">{{ scope.row.publishedRevisionId ? '已发布' : '未发布' }}</el-tag></template></el-table-column><el-table-column label="操作" width="190" fixed="right"><template #default="scope"><el-button link type="primary" icon="Edit" @click="handleEdit(scope.row)" v-hasPermi="['site:credential:edit']">编辑</el-button><el-button v-if="scope.row.draftRevisionId" link type="success" icon="Upload" @click="handlePublish(scope.row)" v-hasPermi="['site:credential:publish']">发布</el-button><el-button v-else-if="scope.row.publishedRevisionId" link type="danger" icon="Remove" @click="handleUnpublish(scope.row)" v-hasPermi="['site:credential:publish']">下架</el-button></template></el-table-column></el-table>
    <div v-if="!loading && !credentialList.length" class="empty"><strong>尚未导入资质证书</strong><span>运行官网迁移包后，软件著作权与专利会在这里统一维护。</span></div><pagination v-show="total > 0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
    <el-dialog :title="dialogTitle" v-model="open" width="800px" append-to-body destroy-on-close><el-alert v-if="form.publishedRevisionId" type="info" :closable="false" show-icon class="mb16" title="当前证书已有公开版本，保存仅更新草稿；发布后才会切换访客可见文件。"/><el-form ref="credentialRef" :model="form" :rules="rules" label-width="120px"><el-form-item label="证书编码" prop="credentialCode"><el-input v-model="form.credentialCode" :disabled="Boolean(form.credentialId)" @input="normalizeCode" /></el-form-item><el-form-item label="证书类型" prop="credentialType"><el-select v-model="form.credentialType" style="width:100%"><el-option v-for="item in types" :key="item.value" :label="item.label" :value="item.value" /></el-select></el-form-item><el-form-item label="证书名称" prop="title"><el-input v-model="form.title" /></el-form-item><el-form-item label="文件媒体编号" prop="documentPublicId"><el-input v-model="form.documentPublicId" placeholder="媒体库内 PDF 的公开编号"/><div class="hint">导入后的证书已预先绑定文件；替换文件时从官网媒体库选择新的 PDF 编号。</div></el-form-item><el-form-item label="内部备注"><el-input v-model="form.remark" type="textarea" :rows="2" /></el-form-item></el-form><template #footer><el-button type="primary" @click="submitForm">保存草稿</el-button><el-button @click="cancel">取消</el-button></template></el-dialog>
  </div>
</template>

<script setup name="SiteCredential">
import { addSiteCredential, getSiteCredential, listSiteCredentials, publishSiteCredential, unpublishSiteCredential, updateSiteCredential } from '@/api/site/credential'
const { proxy } = getCurrentInstance()
const types = [{ label: '软件著作权', value: 'SOFTWARE_COPYRIGHT' }, { label: '专利', value: 'PATENT' }, { label: '其他资质', value: 'OTHER' }]
const loading = ref(false), open = ref(false), credentialList = ref([]), total = ref(0), dialogTitle = ref('')
const emptyForm = () => ({ credentialId: undefined, credentialCode: '', credentialType: 'SOFTWARE_COPYRIGHT', title: '', documentPublicId: '', remark: '', draftRevisionId: undefined, publishedRevisionId: undefined })
const data = reactive({ form: emptyForm(), queryParams: { pageNum: 1, pageSize: 20, credentialCode: undefined, credentialType: undefined }, rules: { credentialCode: [{ required: true, message: '证书编码不能为空', trigger: 'blur' }, { pattern: /^[A-Z][A-Z0-9_]*$/, message: '仅支持大写字母、数字和下划线', trigger: 'blur' }], credentialType: [{ required: true, message: '证书类型不能为空', trigger: 'change' }], title: [{ required: true, message: '证书名称不能为空', trigger: 'blur' }], documentPublicId: [{ required: true, message: '文件媒体编号不能为空', trigger: 'blur' }, { pattern: /^[0-9a-fA-F-]{36}$/, message: '请输入有效的媒体编号', trigger: 'blur' }] } })
const { form, queryParams, rules } = toRefs(data)
function getList() { loading.value = true; listSiteCredentials(queryParams.value).then(res => { credentialList.value = res.rows || []; total.value = res.total || 0 }).finally(() => { loading.value = false }) }
function labelFor(value) { return types.find(item => item.value === value)?.label || value }
function reset() { form.value = emptyForm(); proxy.resetForm('credentialRef') }
function handleQuery() { queryParams.value.pageNum = 1; getList() }
function resetQuery() { proxy.resetForm('queryRef'); handleQuery() }
function normalizeCode(value) { form.value.credentialCode = String(value || '').toUpperCase().replace(/[^A-Z0-9_]/g, '') }
function handleAdd() { reset(); dialogTitle.value = '新增官网资质证书草稿'; open.value = true }
function handleEdit(row) { reset(); getSiteCredential(row.credentialId).then(res => { form.value = { ...emptyForm(), ...res.data }; dialogTitle.value = `编辑资质证书 · ${res.data.credentialCode}`; open.value = true }) }
function cancel() { open.value = false; reset() }
function submitForm() { proxy.$refs.credentialRef.validate(valid => { if (!valid) return; const request = form.value.credentialId ? updateSiteCredential(form.value) : addSiteCredential(form.value); request.then(res => { form.value = { ...form.value, ...res.data }; proxy.$modal.msgSuccess('草稿已保存，尚未影响官网访客'); open.value = false; getList() }) }) }
function handlePublish(row) { proxy.$modal.confirm(`确认直接发布「${row.credentialCode}」的当前草稿吗？访客将立即读取新的证书信息。`).then(() => publishSiteCredential(row.credentialId)).then(() => { proxy.$modal.msgSuccess('已发布'); getList() }) }
function handleUnpublish(row) { proxy.$modal.confirm(`确认下架「${row.credentialCode}」吗？访客将无法继续访问该证书。`).then(() => unpublishSiteCredential(row.credentialId)).then(() => { proxy.$modal.msgSuccess('已下架'); getList() }) }
getList()
</script>

<style scoped lang="scss">.credential-banner{display:flex;justify-content:space-between;gap:24px;align-items:center;padding:22px 24px;margin-bottom:18px;color:#fff;border-radius:16px;background:linear-gradient(120deg,#10294f,#116f9d 60%,#24a4bb)}.credential-banner p{margin:0 0 4px;font-size:11px;letter-spacing:1.4px;opacity:.75}.credential-banner h2{margin:0 0 5px;font-size:24px}.credential-banner span{font-size:13px;opacity:.9}.empty{padding:54px 0;text-align:center;color:#909399}.empty strong,.empty span{display:block}.empty span{margin-top:8px;font-size:13px}.hint{margin-top:6px;color:#909399;font-size:12px;line-height:1.5}@media(max-width:700px){.credential-banner{display:block}.credential-banner .el-button{margin-top:14px}}</style>
